### ISSUE TITLE
SecondViewMediator.onRegister() is never triggered

### ISSUE THREAD

**Issue by ripcurlx** [s9tpepper/robotlegs-starling-plugin#1]
Hi,
thanks for your robotlegs port for Starling. I still have troubles get your example running properly.
I only get log output for "MyGameMediator.onRegister()". The SecondViewMediator is never instantiated.

Do you have an idea what's going wrong?

Thanks,

Christoph

**Comment by ripcurlx** [comment]
I stepped through the code and found that in the StarlingMediatorMap the listeners for the contextView are added (addListeners), but neither Event.ADDED or Event.ADDED_TO_STAGE is triggered. I'll have a look into the Starling code, why these events are not triggered in that case.

**Comment by ripcurlx** [comment]
I just looked into the Starling source code and found out that the Event.ADDED and Event.ADDED_TO_STAGE are not set to bubble up like in the regular Flash display list. :-(

**Comment by ripcurlx** [comment]
I forked the Starling repo and created a fix that fixes the issues with your extension. Fingers crossed that it will be soon merged with the master :-). https://github.com/ripcurlx/Starling-Framework

**Comment by s9tpepper** [comment]
Awesome ripcurlx. I forgot that I had made these changes to the Starling lib so that it bubbles the added to stage events but forgot to submit the patch request to Starling repo.
