### ISSUE TITLE
StarlingActor required?

### ISSUE THREAD

**Issue by eamonnfaherty** [s9tpepper/robotlegs-starling-plugin#10]
There is no StarlingActor class so if creating Actors that dispatch events flash.events.XXX is required.  

This is fine in theory within the Actor (my model) but within the mediators that listen I have starling and flash event types.  

Do you think this is a required addition?

**Comment by FiretronP75** [comment]
It is not required, because you can import both Event classes. However, it is annoying since you have to use the fully qualified path name.

I personally never use starling events in my models tho. What starling events does your model dispatch?

**Comment by thaneros** [comment]
Can someone point me to an example where a model dispatchs an event and a view mediator listens to it?
In my model that extends Actor, I do:

``` as3
dispatch(new AccountEvent(AccountEvent.ACTIVE_ACCOUNT_SELECTED, currentAccount));
```

And in the view mediator that extends StarlingMediator:

``` as3
eventMap.mapListener(eventDispatcher, AccountEvent.ACTIVE_ACCOUNT_SELECTED, activeAccountSelectedHandler, AccountEvent);
```

But the mediator never receives the event. Am I missing something ?

**Comment by FiretronP75** [comment]
Your code here looks correct. Must be something wrong elsewhere in your code. Sorry. :(

**Comment by iambale** [comment]
I have similar problems:

I have a Model extending robotlegs actor and dispatching an non starling event.
in a starling mediator i would like to inject this model but receiving an error "Injector is missing a rule to handle injection into property "model" "
the model is mapped in MainContext and in StarlingContext by injector.mapSingleton(Model);

related to your example the StarlingMediator is a Mediator of MyGame.
On SecondView level injection works pretty well.

Any ideas whats going wrong here?
