### ISSUE TITLE
Coercion failed: Starling Display Object to flash.events.IEventDispatcher. 

### ISSUE THREAD

**Issue by nicholasbester** [s9tpepper/robotlegs-starling-plugin#6]
I get this error whenever I try to listen for an event dispatched from a view. The view extends a Starling Sprite. Any idea what the issue could be?

**Comment by nicholasbester** [comment]
To elaborate on this issue a bit, I have a view which extends a Starling Sprite and I have a mediator for this view which extends StarlingMediator.

I'm dispatching an event from the View which is a custom event subclassing starling.events.Event and I added a listener in the views mediator. I tried different methods provided but all return the same result:

Starling Sprites don't implement IEventDispatcher so I know why I get the error but I assumed this should be the case since this plugin is developed for Starling

**Comment by nicholasbester** [comment]
This seems to be a solution for the time being:
https://github.com/s9tpepper/robotlegs-starling-plugin/issues/4

**Comment by s9tpepper** [comment]
Yea this is a common issue, I'm not sure what a better solution is yet than what we've discussed here: https://github.com/s9tpepper/robotlegs-starling-plugin/issues/4
